import {
  VALID_CDAS_DRAFT_REVIEW_ACTIONS,
  VALID_CDAS_LISTING_REQUESTABILITY_ACTIONS,
  VALID_CDAS_ACCESS_REQUEST_REVIEW_ACTIONS,
} from "./actions.js";

export const uploadAdminRoutePolicy = {
  createsRoutes: true,
  route: "/api/admin/uploads/cdas-document",
  routeStatus: "cdas_draft_document_record_creation_gate",
  adminOnly: true,
  disabledByDefault: true,
  dryRunSupported: true,
  realWriteIntentRecognised: true,
  realWriteDisabledByDefault: true,
  realWriteImplemented: true,
  realWriteRequiresExplicitSwitch: "UPLOAD_ROUTE_REAL_WRITE_ENABLED=true",
  parsesMultipart: true,
  validatesPrefix: true,
  previewsObjectKeys: true,
  calculatesHashEvidence: true,
  checksR2Absence: true,
  createsUploadTransaction: true,
  writesR2: true,
  writesOnlyThroughOrchestrator: true,
  createsDraftCdasDocumentRecord: true,
  draftDocumentStatus: "draft",
  draftDocumentIsListed: 0,
  draftDocumentRequiresApproval: 1,
  activatesDocuments: true,
  makesDocumentsRequestable: true,
  createsAccessRequests: true,
  createsDocumentAccessRequests: true,
  reviewsAccessRequests: true,
  reviewsDocumentAccessRequests: true,
  approvesAccessRequests: true,
  approvesDocumentAccessRequestsForLicencePrep: true,
  generatesPdf: false,
  requiresIdempotencyForRealWrite: true,
  idempotencyField: "client_request_id",
  idempotencyRawKeyStored: false,
  completedReplayWritesR2: false,
  publishesDocuments: false,
  createsLicences: false,
  createsDownloadLinks: false,
  sendsEmail: false,
  exposesAdminVisibilityEvidence: true,
  adminVisibilitySurface: "cdas_documents_admin",
  adminVisibilityPath: "/admin/cdas-documents",
  publicVisibilityCreated: false,
  publicUrlCreated: false,
  adminReviewRequiredBeforeActivation: true,
  createsReviewActionRoute: true,
  reviewActionRoute: "/api/admin/uploads/cdas-document/review",
  reviewActionsRequireExplicitSwitch: "CDAS_UPLOAD_REVIEW_ACTIONS_ENABLED=true",
  validReviewActions: Array.from(VALID_CDAS_DRAFT_REVIEW_ACTIONS),
  reviewActionsActivateDocuments: false,
  reviewActionsPublishDocuments: false,
  reviewActionsGeneratePdf: false,
  reviewActionsCreateLicences: false,
  reviewActionsCreateDownloadLinks: false,
  reviewActionsSendEmail: false,
  createsActivationPrepRoute: true,
  activationPrepRoute: "/api/admin/uploads/cdas-document/activation-prep",
  activationPrepRequiresExplicitSwitch: "CDAS_UPLOAD_ACTIVATION_PREP_ENABLED=true",
  activationPrepRequiresReviewAction: "approve_for_activation_prep",
  createsActivationPrepEvent: true,
  activationPrepActivatesDocuments: false,
  activationPrepPublishesDocuments: false,
  activationPrepMakesDocumentsRequestable: false,
  activationPrepGeneratesPdf: false,
  activationPrepCreatesLicences: false,
  activationPrepCreatesDownloadLinks: false,
  activationPrepSendsEmail: false,
  createsExplicitActivationRoute: true,
  explicitActivationRoute: "/api/admin/uploads/cdas-document/activate",
  explicitActivationRequiresSwitch: "CDAS_UPLOAD_EXPLICIT_ACTIVATION_ENABLED=true",
  explicitActivationRequiresActivationPrep: true,
  explicitActivationChangesStatusToActive: true,
  explicitActivationKeepsDocumentUnlisted: true,
  explicitActivationKeepsApprovalRequired: true,
  explicitActivationCreatesLicence: false,
  explicitActivationCreatesDownloadLink: false,
  explicitActivationGeneratesPdf: false,
  explicitActivationSendsEmail: false,
  createsControlledListingRequestabilityRoute: true,
  controlledListingRequestabilityRoute:
    "/api/admin/uploads/cdas-document/listing-requestability",
  controlledListingRequestabilityRequiresSwitch:
    "CDAS_UPLOAD_LISTING_REQUESTABILITY_ENABLED=true",
  validListingRequestabilityActions:
    Array.from(VALID_CDAS_LISTING_REQUESTABILITY_ACTIONS),
  controlledListingRequiresExplicitActivation: true,
  controlledListingCanSetIsListed: true,
  controlledRequestabilityCanSetRequestableWithApproval: true,
  controlledRequestabilityKeepsApprovalRequired: true,
  controlledRequestabilityMakesDirectDownloadable: false,
  controlledRequestabilityGeneratesPdf: false,
  controlledRequestabilityCreatesLicence: false,
  controlledRequestabilityCreatesDownloadLink: false,
  controlledRequestabilitySendsEmail: false,
  createsControlledAccessRequestIntakeRoute: true,
  controlledAccessRequestIntakeRoute:
    "/api/admin/uploads/cdas-document/access-request",
  controlledAccessRequestIntakeRequiresSwitch:
    "CDAS_UPLOAD_ACCESS_REQUEST_INTAKE_ENABLED=true",
  controlledAccessRequestTargetTable: "document_access_requests",
  controlledAccessRequestRequiresRequestableWithApproval: true,
  controlledAccessRequestCreatesPendingRequest: true,
  controlledAccessRequestStatus: "pending_approval",
  controlledAccessRequestReviewStatus: "pending_review",
  controlledAccessRequestApprovesAccess: false,
  controlledAccessRequestCreatesLicence: false,
  controlledAccessRequestGeneratesPdf: false,
  controlledAccessRequestCreatesDownloadLink: false,
  controlledAccessRequestSendsEmail: false,
  controlledAccessRequestCreatesDirectDownload: false,
  createsControlledAccessRequestReviewRoute: true,
  controlledAccessRequestReviewRoute:
    "/api/admin/uploads/cdas-document/access-request/review",
  controlledAccessRequestReviewRequiresSwitch:
    "CDAS_UPLOAD_ACCESS_REQUEST_REVIEW_ENABLED=true",
  controlledAccessRequestReviewTargetTable:
    "document_access_requests",
  controlledAccessRequestReviewEventTable:
    "document_access_request_review_events",
  validAccessRequestReviewActions:
    Array.from(VALID_CDAS_ACCESS_REQUEST_REVIEW_ACTIONS),
  controlledAccessRequestReviewMayHold: true,
  controlledAccessRequestReviewMayReject: true,
  controlledAccessRequestReviewMayApproveForLicencePrep: true,
  controlledAccessRequestApprovalStatus:
    "approved_pending_licence",
  controlledAccessRequestApprovalReviewStatus:
    "approved_for_licence_prep",
  controlledAccessRequestReviewCreatesLicence: false,
  controlledAccessRequestReviewGeneratesPdf: false,
  controlledAccessRequestReviewCreatesDownloadLink: false,
  controlledAccessRequestReviewSendsEmail: false,
  controlledAccessRequestReviewCreatesDirectDownload: false,
};